import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Baseline schema for the 9 tables this app owns: businesses, users,
 * products, customers, sales, sale_items, expenses, transactions,
 * ledger_events. Hand-authored (not generated by diffing against Supabase)
 * because that database is shared with an unrelated project ("Market OS" —
 * announcements/dues_invoices/levies/market_expenses/market_memberships/
 * markets tables) and already has this exact schema via the old
 * synchronize:true setup, so a live diff would either be empty or risk
 * touching tables this app doesn't own. Every column/index/FK here was
 * verified against Supabase's live information_schema before being
 * written, and this migration was test-run end-to-end in a scratch schema
 * before being recorded as applied (see README).
 *
 * Deliberately NOT included: the orphaned `repayments` table left over
 * from the Repayment→Transaction rename earlier in this project. It still
 * has 3 old rows from before that rename and nothing reads it anymore —
 * left alone rather than dropped as a side effect of an unrelated
 * migrations-adoption change; worth a deliberate cleanup pass later.
 */
export class InitialSchema1790024272338 implements MigrationInterface {
  name = 'InitialSchema1790024272338';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);

    await queryRunner.query(`CREATE TYPE "sales_paymentmethod_enum" AS ENUM ('cash', 'transfer', 'pos', 'credit')`);
    await queryRunner.query(`CREATE TYPE "sales_status_enum" AS ENUM ('draft', 'confirmed', 'cancelled', 'refunded')`);
    await queryRunner.query(
      `CREATE TYPE "sales_paymentstatus_enum" AS ENUM ('unpaid', 'partially_paid', 'paid', 'credit')`,
    );
    await queryRunner.query(
      `CREATE TYPE "expenses_category_enum" AS ENUM ('rent', 'transport', 'salary', 'utilities', 'supplies', 'maintenance', 'other')`,
    );
    await queryRunner.query(
      `CREATE TYPE "transactions_channel_enum" AS ENUM ('cash', 'bank_transfer', 'pos', 'opay', 'palmpay', 'other')`,
    );
    await queryRunner.query(
      `CREATE TYPE "transactions_source_enum" AS ENUM ('merchant_entered', 'provider_feed')`,
    );
    await queryRunner.query(
      `CREATE TYPE "transactions_matchstatus_enum" AS ENUM ('matched', 'unmatched', 'disputed')`,
    );
    await queryRunner.query(`CREATE TYPE "transactions_purpose_enum" AS ENUM ('sale_payment', 'debt_repayment')`);
    await queryRunner.query(`CREATE TYPE "ledger_events_type_enum" AS ENUM (
      'SALE_CREATED', 'PAYMENT_RECEIVED', 'CUSTOMER_CREDIT_CREATED', 'CUSTOMER_CREDIT_REPAID',
      'INVENTORY_DECREASED', 'INVENTORY_ADJUSTED', 'EXPENSE_CREATED', 'PRODUCT_CREATED'
    )`);

    await queryRunner.query(`
      CREATE TABLE "businesses" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "name" character varying NOT NULL,
        "ownerName" character varying,
        "phone" character varying,
        "category" character varying,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_businesses" PRIMARY KEY ("id")
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "users" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "email" character varying NOT NULL,
        "passwordHash" character varying NOT NULL,
        "name" character varying,
        "businessId" uuid NOT NULL,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        "ageConfirmedAt" timestamptz,
        CONSTRAINT "PK_users" PRIMARY KEY ("id"),
        CONSTRAINT "UQ_users_email" UNIQUE ("email"),
        CONSTRAINT "FK_users_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE
      )
    `);

    await queryRunner.query(`
      CREATE TABLE "customers" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "name" character varying NOT NULL,
        "phone" character varying,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_customers" PRIMARY KEY ("id"),
        CONSTRAINT "FK_customers_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_customers_business_name" ON "customers" ("businessId", "name")`);

    await queryRunner.query(`
      CREATE TABLE "products" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "name" character varying NOT NULL,
        "sku" character varying,
        "costPrice" numeric(14,2) NOT NULL,
        "sellingPrice" numeric(14,2) NOT NULL,
        "stockQty" integer NOT NULL DEFAULT 0,
        "lowStockThreshold" integer NOT NULL DEFAULT 0,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        "updatedAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_products" PRIMARY KEY ("id"),
        CONSTRAINT "FK_products_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_products_business_name" ON "products" ("businessId", "name")`);

    await queryRunner.query(`
      CREATE TABLE "sales" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "customerId" uuid,
        "paymentMethod" "sales_paymentmethod_enum" NOT NULL DEFAULT 'cash',
        "status" "sales_status_enum" NOT NULL DEFAULT 'confirmed',
        "paymentStatus" "sales_paymentstatus_enum" NOT NULL DEFAULT 'paid',
        "totalAmount" numeric(14,2) NOT NULL,
        "amountPaid" numeric(14,2) NOT NULL,
        "creditAmount" numeric(14,2) NOT NULL,
        "outstandingBalance" numeric(14,2) NOT NULL DEFAULT '0',
        "costTotal" numeric(14,2) NOT NULL,
        "paymentReference" character varying,
        "verified" boolean NOT NULL DEFAULT false,
        "confirmedAt" timestamptz,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_sales" PRIMARY KEY ("id"),
        CONSTRAINT "FK_sales_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_sales_customer" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_sales_business_createdAt" ON "sales" ("businessId", "createdAt")`);

    await queryRunner.query(`
      CREATE TABLE "sale_items" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "saleId" uuid NOT NULL,
        "productId" uuid NOT NULL,
        "productName" character varying NOT NULL,
        "quantity" integer NOT NULL,
        "unitPrice" numeric(14,2) NOT NULL,
        "unitCostPrice" numeric(14,2) NOT NULL,
        "lineTotal" numeric(14,2) NOT NULL,
        CONSTRAINT "PK_sale_items" PRIMARY KEY ("id"),
        CONSTRAINT "FK_sale_items_sale" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_sale_items_product" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE RESTRICT
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_sale_items_saleId" ON "sale_items" ("saleId")`);
    await queryRunner.query(`CREATE INDEX "IDX_sale_items_productId" ON "sale_items" ("productId")`);

    await queryRunner.query(`
      CREATE TABLE "expenses" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "category" "expenses_category_enum" NOT NULL DEFAULT 'other',
        "amount" numeric(14,2) NOT NULL,
        "description" character varying,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_expenses" PRIMARY KEY ("id"),
        CONSTRAINT "FK_expenses_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_expenses_business_createdAt" ON "expenses" ("businessId", "createdAt")`);

    await queryRunner.query(`
      CREATE TABLE "transactions" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "customerId" uuid,
        "saleId" uuid,
        "channel" "transactions_channel_enum" NOT NULL,
        "source" "transactions_source_enum" NOT NULL DEFAULT 'merchant_entered',
        "matchStatus" "transactions_matchstatus_enum" NOT NULL DEFAULT 'matched',
        "purpose" "transactions_purpose_enum" NOT NULL,
        "amount" numeric(14,2) NOT NULL,
        "reference" character varying,
        "verified" boolean NOT NULL DEFAULT false,
        "note" character varying,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_transactions" PRIMARY KEY ("id"),
        CONSTRAINT "FK_transactions_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE,
        CONSTRAINT "FK_transactions_customer" FOREIGN KEY ("customerId") REFERENCES "customers"("id") ON DELETE SET NULL,
        CONSTRAINT "FK_transactions_sale" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE SET NULL
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_transactions_business_customer" ON "transactions" ("businessId", "customerId")`);
    await queryRunner.query(`CREATE INDEX "IDX_transactions_saleId" ON "transactions" ("saleId")`);

    await queryRunner.query(`
      CREATE TABLE "ledger_events" (
        "id" uuid NOT NULL DEFAULT uuid_generate_v4(),
        "businessId" uuid NOT NULL,
        "type" "ledger_events_type_enum" NOT NULL,
        "amount" numeric(14,2),
        "metadata" jsonb,
        "createdAt" timestamp NOT NULL DEFAULT now(),
        CONSTRAINT "PK_ledger_events" PRIMARY KEY ("id"),
        CONSTRAINT "FK_ledger_events_business" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE
      )
    `);
    await queryRunner.query(`CREATE INDEX "IDX_ledger_events_business_createdAt" ON "ledger_events" ("businessId", "createdAt")`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "ledger_events"`);
    await queryRunner.query(`DROP TABLE "transactions"`);
    await queryRunner.query(`DROP TABLE "expenses"`);
    await queryRunner.query(`DROP TABLE "sale_items"`);
    await queryRunner.query(`DROP TABLE "sales"`);
    await queryRunner.query(`DROP TABLE "products"`);
    await queryRunner.query(`DROP TABLE "customers"`);
    await queryRunner.query(`DROP TABLE "users"`);
    await queryRunner.query(`DROP TABLE "businesses"`);

    await queryRunner.query(`DROP TYPE "ledger_events_type_enum"`);
    await queryRunner.query(`DROP TYPE "transactions_purpose_enum"`);
    await queryRunner.query(`DROP TYPE "transactions_matchstatus_enum"`);
    await queryRunner.query(`DROP TYPE "transactions_source_enum"`);
    await queryRunner.query(`DROP TYPE "transactions_channel_enum"`);
    await queryRunner.query(`DROP TYPE "expenses_category_enum"`);
    await queryRunner.query(`DROP TYPE "sales_paymentstatus_enum"`);
    await queryRunner.query(`DROP TYPE "sales_status_enum"`);
    await queryRunner.query(`DROP TYPE "sales_paymentmethod_enum"`);
  }
}
